steps:
  - name: "node:16"
    entrypoint: "npm"
    args: ["install"]

  - name: "node:16"
    entrypoint: "npm"
    env: ["DISABLE_ESLINT_PLUGIN=true"]
    args: ["run", "build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY
